---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - migration.yml

configMapGenerator:
  - name: fhir-es-migration-script
    options:
      disableNameSuffixHash: true
    files:
      - migrate.sh