---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: clin-qa

resources:
  - ../../common/clin-proxy-api
  - ingresses.yml

patchesStrategicMerge:
  - configmaps.yml
  - deployments.yml

commonLabels:
  group: clin-proxy-api