---
apiVersion: v1
kind: ConfigMap
metadata:
  name: clin-ferload
data:
  AWS_ENDPOINT: https://s3.ops.cqdg.ferlab.bio
  AWS_BUCKET: clin-qa-app-clin-download
  AUTH_ISSUER: https://auth.qa.clin.ferlab.bio/auth/realms/clin
  AUTH_JWKS_URI: https://auth.qa.clin.ferlab.bio/auth/realms/clin/protocol/openid-connect/certs
  AUTH_AUDIENCE: account
  AUTH_URL: https://auth.qa.clin.ferlab.bio/auth/
  AUTH_REALM: clin
  AUTH_CLIENT_ID: clin-acl
  AUTH_SECRET_KEY:
  AUTH_RESOURCES_POLICY_GLOBAL_NAME: download
  AUTH_PUBLIC_CLIENT_ID: clin-client
