---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.clin-fhir-server: "semver:~1"
  name: clin-fhir-server
spec:
  template:
    spec:
      volumes:
        - name: postgres-ca-certificate
          secret:
            secretName: postgres-qa-ca-certificate
            defaultMode: 0555
      imagePullSecrets:
        - name: images-pull
      containers:
        - image: ferlabcrsj/clin-fhir-server:220bafb
          name: clin-fhir-server
          resources:
            requests:
              memory: "2048Mi"
              cpu: "1.00"
            limits:
              memory: "4096Mi"
              cpu: "2.00"
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-qa-fhir-credentials
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-qa-fhir-credentials
                  key: password
            - name: BIO_AUTH_AUTHORIZATION_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-client-acl
                  key: client-secret
          envFrom:
            - configMapRef:
                name: clin-fhir-server
          volumeMounts:
            - name: postgres-ca-certificate
              mountPath: /opt/ca
              readOnly: true
