---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: clin-ferload
    literals:
      - AWS_PATH_ACCESS_STYLE=true
      - AUTH_RESOURCES_POLICY_GLOBAL_NAME=download
