apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: clin-staging

resources:
  - ../cqdg-orchestrations/hive-metastore
  - configs.yml
  - backups

patchesStrategicMerge:
  - deployments.yml
  - service.yml