---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: clin-frontend
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
      - staging.clin.ferlab.bio
      secretName: letsencrypt-certificate
  rules:
    - host: staging.clin.ferlab.bio
      http:
        paths:
        - path: /
          backend:
            serviceName: clin-frontend
            servicePort: 80