apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backup.yml
  - prune-backups.yml

configMapGenerator:
  - name: clin-fhir-server-s3-backups
    options:
      disableNameSuffixHash: false
    literals:
      - S3_ENDPOINT=https://s3.ops.cqdg.ferlab.bio
      - S3_BUCKET=clin-qa-app-fhir-backups
      - S3_REGION=RegionOne
      #15 days
      - S3_BACKUP_MAX_AGE="1296000"
  - name: clin-fhir-server-db-connection
    options:
      disableNameSuffixHash: true
    literals:
      - PGDATABASE=fhir
      - PGHOST=clin-fhir-db-incoming
  - name: clin-fhir-server-db-connection-tls
    options:
      disableNameSuffixHash: true
    literals:
      - PGSSLMODE=verify-full
      - PGSSLROOTCERT=/opt/ca/ca.pem
      - NODE_EXTRA_CA_CERTS=/opt/ca/ca.pem