---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: clin-fhir-server
    literals:
      - BIO_ELASTICSEARCH_HOST=elasticsearch-workers
      - SPRING_DATASOURCE_URL=jdbc:postgresql://__UNDEFINED__:5432/fhir
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQL95Dialect
      - BIO_AUTH_SERVER_URL=https://__UNDEFINED__
      - BIO_AUTH_REALM=clin
      - BIO_AUTH_ENABLED=true
      - BIO_AUTH_AUTHORIZATION_ENABLED=false
      - BIO_AUTH_DISABLE_SSL_VALIDATION=false
      - HAPI_FHIR_SERVER_ADDRESS=https://__UNDEFINED__/fhir/
      - HAPI_FHIR_GRAPHQL_ENABLED=true
      - JAVA_OPTS="-server -Xmx1024m -Djava.net.preferIPv4Stack=true -Djava.awt.headless=true -XX:+UseContainerSupport"
