apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: configure-keycloak
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 15
  jobTemplate:
    spec:
      activeDeadlineSeconds: 1200
      backoffLimit: 0
      template:
        spec:
          imagePullSecrets:
            - name: images-pull
          restartPolicy: Never
          volumes:
            - name: ssh-key
              secret:
                secretName: keycloak-terraform-github-ssh-key
                defaultMode: 0400
            - name: terraform-scripts
              configMap:
                name: terraform-scripts
                defaultMode: 0555
            - name: keycloak-configs-provider
              secret:
                secretName: keycloak-terraform-provider-file
                defaultMode: 0555
            - name: etcd-backend
              configMap:
                name: keycloak-terraform-backend-file
                defaultMode: 0555
            - name: etcd-ca-cert
              secret:
                secretName: etcd-alpha-ops-ca-cert
                defaultMode: 0555
            - name: etcd-client-cert
              secret:
                secretName: etcd-alpha-ops-terraform-keycloak-cert
                defaultMode: 0555
            - name: terraform
              emptyDir: {}
          initContainers:
            - image: ferlabcrsj/git-autosync:10d22c3cab424f19ba9ffc2287aa96170195b27a
              name: clone-repo
              env:
                - name: GIT_REPO
                  value: git@github.com:Ferlab-Ste-Justine/clin-keycloak-configs.git
                - name: GIT_BRANCH
                  value: main
                - name: GIT_PATH
                  value: qa
              command: ["/opt/scripts/clone.sh"]
              volumeMounts:
                - name: ssh-key
                  mountPath: /opt/ssh
                  readOnly: true
                - name: terraform-scripts
                  mountPath: /opt/scripts
                  readOnly: true
                - name: terraform
                  mountPath: /opt/terraform
          containers:
            - image: hashicorp/terraform:0.14.4
              name: configure
              command: ["/opt/scripts/apply.sh"]
              envFrom:
                - secretRef:
                    name: keycloak-terraform-cypress-credentials
              volumeMounts:
                - name: terraform
                  mountPath: /opt/terraform
                - name: terraform-scripts
                  mountPath: /opt/scripts
                  readOnly: true
                - name: keycloak-configs-provider
                  mountPath: /opt/providers
                  readOnly: true
                - name: etcd-backend
                  mountPath: /opt/backend
                  readOnly: true
                - name: etcd-ca-cert
                  mountPath: /opt/etcd-ca
                  readOnly: true
                - name: etcd-client-cert
                  mountPath: /opt/etcd-client-cert
                  readOnly: true