apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: clin-dev

resources:
  - ../cqdg-orchestrations/letsencrypt/genuine

patchesStrategicMerge:
  - issuers.yml
  - certificate.yml