---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: clin-fhir-server
  annotations:
    fluxcd.io/automated: "true"
  name: clin-fhir-server
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: clin-fhir-server
          imagePullPolicy: Never
          name: clin-fhir-server
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: clin-fhir-db-credentials
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: clin-fhir-db-credentials
                  key: password
          resources:
            requests:
              memory: "1024Mi"
              cpu: "1.00"
            limits:
              memory: "2048Mi"
              cpu: "2.00"
