apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: clin-staging

resources:
  - ../cqdg-orchestrations/keycloak
  - ingress.yml
  - configure.yml
  - backups

patchesStrategicMerge:
  - clin-theme.yml
  - keycloak-overrides.yml