name: Validate Manifests

on: [push]

jobs:
  Deploy:
    name: Validate Manifests
    runs-on: ubuntu-18.04
    container: fluxcd/flux:1.21.0
    steps:
    - uses: actions/checkout@v2
    - name: Kustomize Build on QA
      run: kustomize build .
      working-directory: qa