---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/automated: "true"
  name: clin-fhir-server
spec:
  template:
    spec:
      volumes:
        - name: postgres-ca-certificate
          secret:
            secretName: postgres-ca-certificate
            defaultMode: 0555
      imagePullSecrets:
        - name: images-pull
      containers:
        - image: ferlabcrsj/clin-fhir-server:220bafb
          name: clin-fhir-server
          resources:
            requests:
              memory: "2048Mi"
              cpu: "1.00"
            limits:
              memory: "4096Mi"
              cpu: "2.00"
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: clin-fhir-db-credentials
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: clin-fhir-db-credentials
                  key: password
          envFrom:
            - secretRef:
                name: fhir-keycloak-credentials
          volumeMounts:
            - name: postgres-ca-certificate
              mountPath: /opt/ca
              readOnly: true
