---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: clin-fhir-server
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
spec:
  tls:
    - hosts:
      - fhir.qa.clin.ferlab.bio
      secretName: letsencrypt-certificate-temp
  rules:
    - host: fhir.qa.clin.ferlab.bio
      http:
        paths:
        - path: /
          backend:
            serviceName: clin-fhir-server
            servicePort: 8080